variables:
  RUNNER: "next-generation"
  TLEAMS4: "10.233.158.150"
  HOME_DIR: "/home/k113201"
  BASE_DIR: "WebContent"
  SRC_DIR: "WebContent" 
  DEST_DIR: "/data/opt/local-path-provisioner/pvc-43d9c0f2-a83a-4359-91b4-57d262d4dcd8_eams_www-nginx-0" 

.use_cache: &global_cache
  cache:
    - key: websquare
      paths: 
        - .cache/websquare
      policy: pull-push

stages:
  - connection-test
  - ssh-test
  - local-test

connection-test:
  stage: connection-test
  <<: *global_cache
  script:
    - echo > /dev/tcp/$TLEAMS4/22
  only:
    refs:
      - main
  tags:
    - $RUNNER

ssh-test:
  stage: ssh-test
  <<: *global_cache
  before_script:
    - eval $(ssh-agent -s)
    - chmod 400 $ID_RSA
    - ssh-add $ID_RSA
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp $KNOWN_HOSTS ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -i $ID_RSA -l k113201 $TLEAMS4 "id"
  dependencies:
    - connection-test
  only:
    refs:
      - main
  tags:
    - $RUNNER

local-test:
  stage: local-test
  <<: *global_cache
  script:
    - pwd
    - ls -al WebContent
  dependencies:
    - ssh-test
  only:
    refs:
      - main
  tags:
    - $RUNNER