variables:
  RUNNER: "next-generation"
  TLEAMS4: "10.233.158.150"
  USER: "k113201"
  HOME_DIR: "/home/k113201"

stages:
  - connection-test
  - web-contents-deploy

connection-test:
  stage: connection-test
  script:
    - echo > /dev/tcp/$TLEAMS4/22
  rules:
    - if: $CI_COMMIT_REF_NAME == "main" && $CI_COMMIT_TAG
      changes:
        - WebContent/**/*
    - if: $FORCE_DEPLOY == "true"
  tags:
    - $RUNNER

web-contents-deploy:
  stage: web-contents-deploy
  before_script:
    - eval $(ssh-agent -s)
    - chmod 400 $ID_RSA
    - ssh-add $ID_RSA
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp $KNOWN_HOSTS ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -i $ID_RSA -l $USER $TLEAMS4 "if [ -d WebContent ];then mv WebContent{,.old}; fi"
    - ssh -i $ID_RSA -l $USER $TLEAMS4 "if [ -d WebContent.old ];then rm -rf WebContent.old; fi"
    - scp -i $ID_RSA -r WebContent $USER@$TLEAMS4:$HOME_DIR/WebContent
    - ssh -i $ID_RSA -l $USER $TLEAMS4 "if [ -d WebContent ];then chmod -R 755 WebContent; fi"
    - ssh -i $ID_RSA -l $USER $TLEAMS4 "bash $HOME_DIR/wpack-build.sh"
  dependencies:
    - connection-test
  rules:
    - if: $CI_COMMIT_REF_NAME == "main" && $CI_COMMIT_TAG
      changes:
        - WebContent/**/*
    - if: $FORCE_DEPLOY == "true"
  when: manual
  tags:
    - $RUNNER