/*amd /page/component/CMDBManagementDashboard.xml 3157 e45ba4d702bb9e61dac31336e486300a650b61bb9b2d72bb70fbec2e14e1635e */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',A:{},E:[{T:1,N:'w2:type',E:[{T:3,text:'COMPONENT'}]},{T:1,N:'w2:buildDate'},{T:1,N:'w2:MSA'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',A:{baseNode:'map'}},{T:1,N:'w2:workflowCollection'}]},{T:1,N:'w2:layoutInfo'},{T:1,N:'w2:publicInfo',A:{method:''}},{T:1,N:'script',A:{lazy:'false',type:'text/javascript'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){scwin.onpageload = function () {
  let widgetOptions1 = {};
  widgetOptions1.id = "wg_widget1";
  widgetOptions1.src = "/page/widget/WidgetLatestSearchKeyword.xml";
  widgetOptions1.scope = true;
  widgetOptions1.unitWidth = 5;
  widgetOptions1.unitHeight = 10;
  widgetOptions1.title = "Server";
  widgetOptions1.x = 0;
  widgetOptions1.y = 0;
  wgc_contain.addWidgets(widgetOptions1);
  let widgetOptions2 = {};
  widgetOptions2.id = "wg_widget2";
  widgetOptions2.src = "/page/widget/WidgetLatestVisited.xml";
  widgetOptions2.scope = true;
  widgetOptions2.unitWidth = 5;
  widgetOptions2.unitHeight = 10;
  widgetOptions2.title = "Storage";
  widgetOptions2.x = 5;
  widgetOptions2.y = 0;
  wgc_contain.addWidgets(widgetOptions2);
  let widgetOptions3 = {};
  widgetOptions3.id = "wg_widget3";
  widgetOptions3.src = "/page/widget/WidgetLatestChangedTR.xml";
  widgetOptions3.scope = true;
  widgetOptions3.unitWidth = 5;
  widgetOptions3.unitHeight = 10;
  widgetOptions3.title = "Network";
  widgetOptions3.x = 0;
  widgetOptions3.y = 5;
  wgc_contain.addWidgets(widgetOptions3);
  let widgetOptions4 = {};
  widgetOptions4.id = "wg_widget4";
  widgetOptions4.src = "/page/widget/WidgetLatestChangedScreen.xml";
  widgetOptions4.scope = true;
  widgetOptions4.unitWidth = 5;
  widgetOptions4.unitHeight = 10;
  widgetOptions4.title = "Middleware";
  widgetOptions4.x = 5;
  widgetOptions4.y = 5;
  wgc_contain.addWidgets(widgetOptions4);
  let widgetOptions5 = {};
  widgetOptions5.id = "wg_widget5";
  widgetOptions5.src = "/page/widget/WidgetLatestChangedTR.xml";
  widgetOptions5.scope = true;
  widgetOptions5.unitWidth = 5;
  widgetOptions5.unitHeight = 10;
  widgetOptions5.title = "보안 장비";
  // widgetOptions5.x = 0;
  // widgetOptions5.y = 5;
  wgc_contain.addWidgets(widgetOptions5);
  let widgetOptions6 = {};
  widgetOptions6.id = "wg_widget6";
  widgetOptions6.src = "/page/widget/WidgetLatestChangedScreen.xml";
  widgetOptions6.scope = true;
  widgetOptions6.unitWidth = 5;
  widgetOptions6.unitHeight = 10;
  widgetOptions6.title = "업무 시스템";
  widgetOptions6.x = 5;
  // widgetOptions6.y = 5;
  wgc_contain.addWidgets(widgetOptions6);
};
}}}]}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload',style:';background-color:;'},E:[{T:1,N:'xf:group',A:{id:'',style:'width:100%;height:100%;background-color:;padding: 24px;box-sizing: border-box;'},E:[{T:1,N:'w2:widgetContainer',A:{cols:'10',horizontalMargin:'10',id:'wgc_contain',mode:'',params:'false',style:'width: 100%;height: 100%;'}}]}]}]}]})