/*amd /page/LoginPage.xml 3062 38f7a132373d355b0328fb24254147e2ddcc876c6fc57f790894e85961a52de6 */
define({declaration:{A:{version:'1.0',encoding:'UTF-8'}},E:[{T:1,N:'html',A:{xmlns:'http://www.w3.org/1999/xhtml','xmlns:ev':'http://www.w3.org/2001/xml-events','xmlns:w2':'http://www.inswave.com/websquare','xmlns:xf':'http://www.w3.org/2002/xforms'},E:[{T:1,N:'head',A:{},E:[{T:1,N:'w2:type',E:[{T:3,text:'COMPONENT'}]},{T:1,N:'w2:buildDate'},{T:1,N:'w2:MSA'},{T:1,N:'xf:model',E:[{T:1,N:'w2:dataCollection',A:{baseNode:'map'},E:[{T:1,N:'w2:dataList',A:{baseNode:'list',repeatNode:'map',id:'dataList1',saveRemovedData:'true'},E:[{T:1,N:'w2:columnInfo'}]},{T:1,N:'w2:dataMap',A:{baseNode:'map',id:'dataMap1'},E:[{T:1,N:'w2:keyInfo',E:[{T:1,N:'w2:key',A:{id:'userId',name:'userId',dataType:'number'}},{T:1,N:'w2:key',A:{id:'id',name:'id',dataType:'number'}},{T:1,N:'w2:key',A:{id:'title',name:'title',dataType:'text'}},{T:1,N:'w2:key',A:{id:'completed',name:'completed',dataType:'number'}}]}]}]},{T:1,N:'w2:workflowCollection'},{T:1,N:'xf:submission',A:{id:'submission1',action:'http://10.50.241.179:8081/org/api/v1/command/emp-login',method:'post',mediatype:'application/json',ref:'',target:'data:json,dataMap1',encoding:'UTF-8',instance:'',replace:'',errorHandler:'',customHandler:'',mode:'asynchronous',processMsg:'','ev:submit':'','ev:submitdone':'','ev:submiterror':'',abortTrigger:''}}]},{T:1,N:'w2:layoutInfo'},{T:1,N:'w2:publicInfo',A:{method:''}},{T:1,N:'script',A:{lazy:'false',type:'text/javascript'},E:[{T:4,cdata:function(scopeObj){with(scopeObj){scwin.onpageload = function () {
  $p.executeSubmission("submission1", {
    "empNo": "113565",
    "pwd": "cdk200022"
  });
};
scwin.btnLoginClick_onclick = function (e) {
  $p.url("/page/layout/TopNavigationBottomContents.xml");
};
}}}]}]},{T:1,N:'body',A:{'ev:onpageload':'scwin.onpageload',style:'background-color:#0E2147;display:flex;justify-content: center;align-items: center;'},E:[{T:1,N:'xf:group',A:{style:'width:314px;height:266px;display: flex;flex-direction: column;gap: 12px;',id:''},E:[{T:1,N:'xf:group',A:{style:'position:static;top:242px;left:423px;width:100%;height:100px;display: flex;justify-content: center;align-items: center;',id:''},E:[{T:1,N:'xf:image',A:{src:'/img/loginLogo.svg',style:'width: 244px;height: 72px;',id:''}}]},{T:1,N:'xf:group',A:{style:'top:242px;left:423px;width:100%;display: flex;gap: 8px;flex-direction: column;justify-content: center;align-items: center;',id:''},E:[{T:1,N:'xf:input',A:{style:'position:static;top:152px;left:272px;width:314px;height:40px;',id:'',placeholder:'사번'}},{T:1,N:'xf:input',A:{style:'position:static;top:152px;left:272px;width:314px;height:40px;',id:'',placeholder:'패스워드'}}]},{T:1,N:'xf:group',A:{style:'position:static;top:242px;left:423px;width:100%;height:48px;display: flex;justify-content: center;align-items: center;',id:''},E:[{T:1,N:'w2:button',A:{'ev:onclick':'scwin.btnLoginClick_onclick',style:'position:static;top:318px;left:153px;width:314px;height:48px;background-color:#3761BB;color:#FFFFFF;font-size:18px;font-weight:bold;border-width:0px;border-radius: 8px;',id:'btnLoginClick',label:'로그인'}}]}]}]}]}]})